/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 * Created on May 29, 2013, 5:35:52 PM
 */

/**
 *
 * @author pc world
 
*/
import java.sql.
*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
public class LogIn extends javax.swing.JFrame
 {
    DbConn obj=new DbConn();

    /** Creates new form LogIn */
    
public LogIn() 
{
        
initComponents();
  
  }

    /** This method is called from within the constructor to
     * initialize the form.
    
 * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
private void initComponents() 
{


        jScrollPane1 = new javax.swing.JScrollPane();
      
  jTextArea1 = new javax.swing.JTextArea();
     
   jLabel1 = new javax.swing.JLabel();
   
     jLabel2 = new javax.swing.JLabel();
    
    txtid = new javax.swing.JTextField();
      
  jLabel3 = new javax.swing.JLabel();
     
   jButton1 = new javax.swing.JButton();
     
   lblout = new javax.swing.JLabel();
       
 jLabel4 = new javax.swing.JLabel();
        
txtpass = new javax.swing.JPasswordField();

    
    jTextArea1.setColumns(20);
    
    jTextArea1.setRows(5);
       
 jScrollPane1.setViewportView(jTextArea1);

  
      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

     
   jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
      
  jLabel1.setText("    IFTIKHAR MEDICAL STORE");

    
    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
  
      jLabel2.setText("Enter UserName:");

      
  jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
  
      jLabel3.setText("Enter Password:");

    
    jButton1.setBackground(new java.awt.Color(204, 204, 204));
   
     jButton1.setText("ENTER");
     
   jButton1.addActionListener(new java.awt.event.ActionListener() 
{
           
 public void actionPerformed(java.awt.event.ActionEvent evt)
 {
               
 jButton1ActionPerformed(evt);
    
        }
        });

   
     jLabel4.setText("Copyrights © Iftikhar shah");

      
  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       
 getContentPane().setLayout(layout);
   
     layout.setHorizontalGroup(
   
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    
        .addGroup(layout.createSequentialGroup()
      
          .addContainerGap()
            
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblout, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addComponent(lblout, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String username=txtid.getText();
        String password=txtpass.getText();
        String query= "Select* From Employee Where UserName='"+username+"' AND Password= '"+password+"'";
        ResultSet rs=obj.Search(query);
        try {
            if (rs.next()) {
                MainForm mf = new MainForm();
                mf.setVisible(true);
            } else {
                lblout.setText("Alert!Invalid I.D or PASS");
                txtid.setText("");
                txtpass.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblout;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables

}
